"""Persona auth and permissions

Revision ID: cda6dcdb87
Revises: 58c21256267
Create Date: 2014-03-30 00:05:57.993849

"""

# revision identifiers, used by Alembic.
revision = 'cda6dcdb87'
down_revision = '58c21256267'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.UnicodeText(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_groups_name', 'groups', ['name'], unique=True)
    op.create_table('user_groups',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.add_column('users', sa.Column('email', sa.UnicodeText(), nullable=False, server_default=''))
    op.alter_column('users', 'email', server_default=None)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'email')
    op.drop_table('user_groups')
    op.drop_index('ix_groups_name', table_name='groups')
    op.drop_table('groups')
    ### end Alembic commands ###
