"""Added comic transcripts

Revision ID: 58c21256267
Revises: None
Create Date: 2014-02-18 22:26:33.521986

"""

# revision identifiers, used by Alembic.
revision = '58c21256267'
down_revision = None
branch_labels = ('comic',)

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comic_page_transcripts',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Unicode(length=2), nullable=False),
    sa.Column('transcript', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['comic_pages.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'language')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comic_page_transcripts')
    ### end Alembic commands ###
