"""empty message

Revision ID: 1dea06bc811
Revises: 11e7d88c74e
Create Date: 2015-02-01 19:47:41.174366

"""

# revision identifiers, used by Alembic.
revision = '1dea06bc811'
down_revision = '11e7d88c74e'
branch_labels = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column('users', sa.Column('password', sa.Unicode(), nullable=False, server_default=''))
    op.alter_column('users', 'password', server_default=None)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
